"""Generate REINVENT4 TOML configuration from user input."""

from typing import Any

from app.schemas.task import TaskSubmitRequest, TargetOverride, ScoringComponentSpec


class TOMLGenerator:
    """Generate a staged_learning TOML config for REINVENT4 with DockStream scoring."""

    MODE_CONFIGS = {
        "reinvent": {
            "prior_file": "/app/REINVENT4/prior/reinvent.prior",
            "agent_file": "/app/REINVENT4/prior/reinvent.prior",
        },
        "libinvent": {
            "prior_file": "/app/REINVENT4/prior/libinvent.prior",
            "agent_file": "/app/REINVENT4/prior/libinvent.prior",
        },
        "linkinvent": {
            "prior_file": "/app/REINVENT4/prior/linkinvent.prior",
            "agent_file": "/app/REINVENT4/prior/linkinvent.prior",
        },
    }

    def __init__(
        self,
        request: TaskSubmitRequest,
        targets: list[Any],
    ):
        self.request = request
        self.targets = targets
        self.mode_config = self.MODE_CONFIGS.get(request.mode, self.MODE_CONFIGS["reinvent"])

    def generate(self) -> str:
        lines = []
        self._write_header(lines)
        self._write_parameters(lines)
        self._write_learning_strategy(lines)
        self._write_diversity_filter(lines)
        self._write_stage(lines)
        return "\n".join(lines) + "\n"

    def _write_header(self, lines: list[str]):
        lines.append("# REINVENT4 RL config generated by De novo Platform")
        lines.append(f"# mode: {self.request.mode}")
        lines.append("")
        lines.append('run_type = "staged_learning"')
        lines.append(f'device = "{self.request.device}"')
        lines.append('tb_logdir = "/output/tb_logs"')
        lines.append('json_out_config = "_config.json"')
        lines.append("")

    def _write_parameters(self, lines: list[str]):
        lines.append("[parameters]")
        lines.append(f'summary_csv_prefix = "/output/run"')
        lines.append("use_checkpoint = false")
        lines.append("purge_memories = false")
        lines.append("")
        lines.append(f'prior_file = "{self.mode_config["prior_file"]}"')
        lines.append(f'agent_file = "{self.mode_config["agent_file"]}"')
        lines.append("")
        lines.append(f"batch_size = {self.request.batch_size}")
        lines.append("unique_sequences = true")
        lines.append("randomize_smiles = true")
        lines.append("tb_isim = false")
        lines.append("")

    def _write_learning_strategy(self, lines: list[str]):
        lines.append("[learning_strategy]")
        lines.append('type = "dap"')
        lines.append(f"sigma = {self.request.sigma}")
        lines.append(f"rate = {self.request.learning_rate}")
        lines.append("")

    def _write_diversity_filter(self, lines: list[str]):
        lines.append("[diversity_filter]")
        lines.append('type = "IdenticalMurckoScaffold"')
        lines.append("bucket_size = 25")
        lines.append("minscore = 0.4")
        lines.append("minsimilarity = 0.4")
        lines.append("penalty_multiplier = 0.5")
        lines.append("")

    def _write_stage(self, lines: list[str]):
        lines.append("[[stage]]")
        lines.append('chkpt_file = "/output/agent.chkpt"')
        lines.append('termination = "simple"')
        lines.append(f"max_steps = {self.request.max_steps}")
        lines.append("max_score = 1.0")
        lines.append(f"min_steps = {self.request.max_steps}")
        lines.append("")
        lines.append("[stage.scoring]")
        lines.append(f'type = "{self.request.aggregation}"')
        lines.append("")

        for i, target_dto in enumerate(self.targets):
            self._write_dockstream_component(lines, target_dto, i)

        for comp in self.request.extra_components:
            self._write_extra_component(lines, comp)

    def _write_dockstream_component(self, lines: list[str], target_dto, idx: int):
        target = target_dto["target"]
        override = target_dto.get("override")
        config_path = target_dto.get("config_path", f"/data/config/dockstream_target{idx+1}.json")

        weight = override.weight if override and override.weight else 1.0
        transform_high = target_dto.get("transform_high", -6.0)
        transform_low = target_dto.get("transform_low", -14.5)  # Updated from -13.5
        transform_k = target_dto.get("transform_k", 0.2)

        lines.append("[[stage.scoring.component]]")
        lines.append('[stage.scoring.component.DockStream]')
        lines.append("")
        lines.append("[[stage.scoring.component.DockStream.endpoint]]")
        lines.append(f'name = "Docking_{target.name}"')
        lines.append(f"weight = {weight}")
        lines.append(f'params.configuration_path = "{config_path}"')
        lines.append('params.docker_script_path = "/app/DockStream/docker.py"')
        lines.append('params.docker_python_path = "/opt/conda_envs/dockstream_env/bin/python"')
        lines.append("")
        lines.append("[stage.scoring.component.DockStream.endpoint.transform]")
        lines.append('type = "reverse_sigmoid"')
        lines.append(f"high = {transform_high}")
        lines.append(f"low = {transform_low}")
        lines.append(f"k = {transform_k}")
        lines.append("")

    def _write_extra_component(self, lines: list[str], comp: ScoringComponentSpec):
        lines.append("[[stage.scoring.component]]")
        comp_type = comp.type
        lines.append(f"[stage.scoring.component.{comp_type}]")
        lines.append(f'name = "{comp.name}"')
        lines.append("")
        lines.append(f"[[stage.scoring.component.{comp_type}.endpoint]]")
        lines.append(f'name = "{comp.name}"')
        lines.append(f"weight = {comp.weight}")
        if comp.params:
            for key, value in comp.params.items():
                if isinstance(value, list):
                    lines.append(f"params.{key} = {value}")
                elif isinstance(value, str):
                    lines.append(f'params.{key} = "{value}"')
                else:
                    lines.append(f"params.{key} = {value}")
        
        # Add transform
        if comp.transform:
            lines.append("")
            lines.append(f"[stage.scoring.component.{comp_type}.endpoint.transform]")
            lines.append(f'type = "{comp.transform.type}"')
            if comp.transform.high is not None:
                lines.append(f"high = {comp.transform.high}")
            if comp.transform.low is not None:
                lines.append(f"low = {comp.transform.low}")
            if comp.transform.k is not None:
                lines.append(f"k = {comp.transform.k}")
            if comp.transform.coef_div is not None:
                lines.append(f"coef_div = {comp.transform.coef_div}")
            if comp.transform.coef_si is not None:
                lines.append(f"coef_si = {comp.transform.coef_si}")
            if comp.transform.coef_se is not None:
                lines.append(f"coef_se = {comp.transform.coef_se}")
            if comp.transform.slope is not None:
                lines.append(f"slope = {comp.transform.slope}")
            if comp.transform.intercept is not None:
                lines.append(f"intercept = {comp.transform.intercept}")
        else:
            # Auto-add transform for components that need it
            if comp_type == "SAscore":
                # SAscore: 1-10 range, lower is better
                lines.append("")
                lines.append(f"[stage.scoring.component.{comp_type}.endpoint.transform]")
                lines.append('type = "reverse_sigmoid"')
                lines.append("high = 10.0")
                lines.append("low = 1.0")
                lines.append("k = 0.2")
            elif comp_type == "QED":
                # QED: 0-1 range, higher is better - no transform needed
                pass
        lines.append("")
